### ISSUE TITLE
Dev package

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-mirror-feedstock#8]
Hi @ericdill @parente - I would like to release a development version of conda-mirror (onto  `conda-forge/label/dev`, like we do with some other packages). 

Do either of you have any objections to this? Also, I put in a PR to add myself as a maintainer.

**Comment by scopatz** [comment]
pinging this @ericdill @parente!

**Comment by ericdill** [comment]
@scopatz is this still an open issue? I am sort of assuming you just did this already (which I'd be totally fine with)

**Comment by scopatz** [comment]
Yeah, this is no longer valid
